version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=foodappdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foodapppsw
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - 5432:5432 
